# Generated by Django 5.2.1 on 2025-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('STD', 'Standard'), ('PRM', 'Premium'), ('VIP', 'VIP')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
